# Generated by Django 5.2.3 on 2025-07-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('markings_count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('marking_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.markingimport')),
            ],
        ),
    ]
